server:
  port: 8081

spring:
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: admin
    send-timeout: 5
    pool:
      enabled: false
      idle-timeout: 30s
      max-connections: 50
      max-sessions-per-connection: 100
  jms:
    session-cache-size: 5